# Generated by Django 4.0.5 on 2022-08-04 08:35

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filepath', models.CharField(max_length=255)),
                ('row', models.IntegerField()),
                ('type', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('old_text', models.TextField(default='')),
                ('user_session_id', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filepath', models.CharField(max_length=255)),
                ('row_start', models.IntegerField()),
                ('row_end', models.IntegerField()),
                ('col_start', models.IntegerField()),
                ('col_end', models.IntegerField()),
                ('type', models.CharField(max_length=255)),
                ('has_new_content', models.BooleanField(default=False)),
                ('new_content', models.TextField(default='')),
                ('sync_id', models.IntegerField(default=0)),
                ('user_id', models.IntegerField()),
                ('user_alias', models.CharField(max_length=255)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('user_alias', models.CharField(max_length=255)),
                ('latest_activity', models.DateTimeField(default=django.utils.timezone.now)),
                ('activity_file', models.CharField(max_length=255)),
                ('activity_position_line', models.IntegerField(default=0)),
                ('activity_position_col', models.IntegerField(default=0)),
                ('activity_row_start', models.IntegerField(default=0)),
                ('activity_row_end', models.IntegerField(default=0)),
                ('activity_col_start', models.IntegerField(default=0)),
                ('activity_col_end', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('user_id', models.IntegerField()),
                ('user_alias', models.CharField(max_length=255)),
                ('initial', models.BooleanField(default=False)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('mark', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='editor.mark')),
            ],
        ),
    ]
