# Generated by Django 4.0.5 on 2022-11-17 23:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0002_user_lines_added_user_lines_changed_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('day', models.DateField(default=django.utils.timezone.now)),
                ('lines_added', models.IntegerField(default=0)),
                ('lines_deleted', models.IntegerField(default=0)),
                ('lines_changed', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='lines_added',
        ),
        migrations.RemoveField(
            model_name='user',
            name='lines_changed',
        ),
        migrations.RemoveField(
            model_name='user',
            name='lines_deleted',
        ),
    ]
