# Generated by Django 4.0.5 on 2022-11-18 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0003_userstat_remove_user_lines_added_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstat',
            name='user_alias',
            field=models.CharField(default='Kevin', max_length=255),
            preserve_default=False,
        ),
    ]
